import { Metadata } from "next";

// export const metaData: Metadata = {
//   title: "Home | Next.js",
//   description: "Generated by create next app",
// };

export default function Home() {
  return (
    <>
      <h1 className="heading">Home</h1>
    </>
  );
}
