import { Metadata } from "next";
import Image from "next/image";

export const metaData: Metadata = {
  title: "Home | Next.js",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <>
      <h1 className="text-2xl">Home</h1>
    </>
  );
}
